---
- name: Ansible Playbook
  hosts: localhost
  sudo: True

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: nickbakker/tomcat

    - name: Build Docker image
      docker_image:
        path: /tmp
        name: nickbakker/tomcat
        buildargs:
          log_volume: /var/log/myapp
          listen_port: 8080
